#!/usr/bin/env python3
"""Build the inline brush font used by fixed UI labels.

Run from any directory after npm ci:
    python -m pip install 'fonttools[woff]'
    python scripts/build-brush-critical.py

The source is the existing @fontsource/ma-shan-zheng package, licensed under
the SIL Open Font License (see public/fonts/licenses/MaShanZheng-OFL.txt).
No source font or additional npm dependency is downloaded by this script.
"""

from __future__ import annotations

import base64
import io
import json
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "node_modules/@fontsource/ma-shan-zheng/files/ma-shan-zheng-chinese-simplified-400-normal.woff2"
OUTPUT = ROOT / "src/app/brush-critical.css"
TEXT = (
    "昨日头条日签 0123456789年月日 · 历史日签 "
    "往日，值得重读。把喜欢的历史留下。"
    "这里，留给你喜欢的故事。这个分类暂时没有内容。"
    "这一天的资料，正在等待补齐。这一天，暂留一页空白。终。"
)
# The Chinese source font has no middle dot. Omitting it from unicode-range
# deliberately lets the existing fallback font draw that punctuation.
FALLBACK_CODEPOINTS = {0x00B7}


def main() -> None:
    font = TTFont(SOURCE, recalcTimestamp=False)
    requested = {ord(character) for character in TEXT}
    source_codepoints = set(font.getBestCmap())
    missing = requested - source_codepoints
    unexpected_missing = missing - FALLBACK_CODEPOINTS
    if unexpected_missing:
        raise ValueError(
            "Source font is missing required UI characters: "
            + ", ".join(f"U+{value:04X}" for value in sorted(unexpected_missing))
        )

    options = subset.Options()
    options.flavor = "woff2"
    options.recalc_timestamp = False
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=sorted(requested & source_codepoints))
    subsetter.subset(font)
    font.flavor = "woff2"

    buffer = io.BytesIO()
    font.save(buffer)
    payload = buffer.getvalue()
    # Derive the range from the written font, rather than assuming the
    # subsetter retained exactly the requested Unicode mappings.
    rebuilt = TTFont(io.BytesIO(payload), recalcTimestamp=False)
    actual_codepoints = set(rebuilt.getBestCmap())
    if actual_codepoints != requested - missing:
        raise ValueError("Generated font coverage differs from requested UI text")
    unicode_range = ",".join(f"U+{value:04X}" for value in sorted(actual_codepoints))
    encoded = base64.b64encode(payload).decode("ascii")
    css = (
        "/* Generated by scripts/build-brush-critical.py; do not edit manually.\n"
        " * Ma Shan Zheng, SIL OFL: public/fonts/licenses/MaShanZheng-OFL.txt\n"
        " * Fixed UI only; U+00B7 (middle dot) uses the normal fallback font. */\n"
        "@font-face {\n"
        "  font-family: 'Headlines UI Brush';\n"
        "  font-style: normal;\n"
        "  font-weight: 400;\n"
        "  font-display: block;\n"
        f"  src: url(data:font/woff2;base64,{encoded}) format('woff2');\n"
        f"  unicode-range: {unicode_range};\n"
        "}\n"
    )
    OUTPUT.write_text(css, encoding="utf-8", newline="\n")
    print(json.dumps({
        "output": str(OUTPUT.relative_to(ROOT)),
        "woff2Bytes": len(payload),
        "cssBytes": len(css.encode("utf-8")),
        "unicodeCharacters": len(actual_codepoints),
        "glyphs": len(rebuilt.getGlyphOrder()),
        "fallbackCodepoints": [f"U+{value:04X}" for value in sorted(missing)],
    }))


if __name__ == "__main__":
    main()
